[package]
name = "CMD_To_Do"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
sqlite = "0.36.0"
crossterm = "0.27.0"
anyhow = "1.0.86"
clearscreen = "3.0.0"
